version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: leads-mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DB_NAME}
    volumes:
      - mongodb_data:/data/db
    networks:
      - leads-network

  api:
    build: .
    container_name: leads-api
    ports:
      - "8000:8000"
    environment:
      MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/?authSource=admin
      MONGODB_DB_NAME: ${MONGODB_DB_NAME}
      EXTERNAL_API_URL: ${EXTERNAL_API_URL}
    depends_on:
      - mongodb
    volumes:
      - ./app:/app/app
    networks:
      - leads-network

volumes:
  mongodb_data:

networks:
  leads-network:
    driver: bridge
